[package]
name = "jimmy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axe = { git = "https://github.com/3-lines-studio/axe", rev = "0c4f739935e83d381313bf23f18100dc162d0a4b" }
heimdall = { git = "https://github.com/3-lines-studio/heimdall", rev = "0973bef70b2f3791547addde1b2810f53efbbe93" }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1.6"
tungstenite = { version = "0.30", features = ["rustls-tls-webpki-roots"] }
ureq = "2"
