[package]
name = "jimmy"
version = "0.1.0"
edition = "2021"

[dependencies]
axe = { git = "https://github.com/3-lines-studio/axe", rev = "fe32d18db059568bd52dbaabd692f602ac186720" }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1.6"
tungstenite = { version = "0.30", features = ["rustls-tls-webpki-roots"] }
ureq = "2"
