[package]
name = "jimmy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axe = { git = "https://github.com/3-lines-studio/axe", rev = "fe67edec43da62263d1949519babe95c126961ab", default-features = false }
heimdall = { git = "https://github.com/3-lines-studio/heimdall", rev = "d7d2b201aa091f022f94f6fd1653c19655738a71" }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1.6"
tungstenite = { version = "0.30", features = ["rustls-tls-webpki-roots"] }
ureq = "2"
